apiVersion: apps/v1
kind: Deployment
metadata:
  name: syugoshin
  labels:
    app: syugoshin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syugoshin
  template:
    metadata:
      labels:
        app: syugoshin
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                      - oracle
      containers:
        - name: syugoshin
          image: ghcr.io/mo-tomi/shugoshin-bot-v2:edge
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: syugoshin-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
